name: Stylism
favicon: null
layout_spectrum: 0
typography_spectrum: 0.850050425156951
title: style for your home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9d9d9'
    - '#4f564e'
    - '#1c2719'
    - '#9fafac'
    - '#af8461'
  brandStrength: 1
  lightness: 0.9958576834760606
  saturation: 0.05743156839162111
  rhythmicContrast: 0.07359267235733569
purpose: []
