name: Stylism
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49324
title: style for your home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5aabea'
    - '#327794'
    - '#1c4229'
  brandStrength: 1
  lightness: 0.9958576834760606
  saturation: 0
  rhythmicContrast: 0
purpose: []
