name: Stylism
favicon: null
layout_spectrum: 0
typography_spectrum: 0.850050425156951
title: style for your home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eee2cc'
    - '#93bcae'
    - '#434238'
    - '#4e9783'
  brandStrength: 1
  lightness: 0.9958576834760606
  saturation: 0.05743156839162111
  rhythmicContrast: 0.07359267235733569
purpose: []
